#!/bin/bash

LOW=20
TOO_LOW=10
SLEEP_TIME=60

while true ; do

    CHARGING_STATUS=`acpi -b | grep -P -o '[A-z]+(?=,)'`
    CURRENT_BATTERY=`acpi -b | grep -P -o '[0-9]+(?=%)'`

    [[ ! -f "~/.is_battery_notify_sent" ]] && touch ~/.is_battery_notify_sent

    IS_NOTIFY_SENT=`cat ~/.is_battery_notify_sent`

    if [[ $CHARGING_STATUS = "Discharging" ]]; then

	if [[ $IS_NOTIFY_SENT -ne "2" && $CURRENT_BATTERY -le $TOO_LOW ]]; then
	    echo "2" > ~/.is_battery_notify_sent
            /usr/bin/notify-send -u critical "Extremely Low Battery" "Battery level is `echo $CURRENT_BATTERY`%!"
	    
	elif [[ $IS_NOTIFY_SENT -ne "1" && $CURRENT_BATTERY -le $LOW && $CURRENT_BATTERY -gt $TOO_LOW ]]; then
	    echo "1" > ~/.is_battery_notify_sent
	    /usr/bin/notify-send -u critical "Low Battery" "Battery level is `echo $CURRENT_BATTERY`%!"
	fi
	
    else
	if [[ $IS_NOTIFY_SENT -ne "0" ]]; then
	    echo "0" > ~/.is_battery_notify_sent
	fi
    fi

    sleep $SLEEP_TIME
    
done
